ACCEPT v_especialidade CHAR PROMPT 'Informe a especialidade: '
SET PAGESIZE 200
SET LINESIZE 200

COLUMN NOME                  HEADING 'ESPECIALIDADE' FORMAT A30
COLUMN VALOR                 HEADING 'VALOR_FATURADO' FORMAT 9,999.99

SELECT
    E.DESCRICAO AS NOME,
    SUM(PA.VALOR) AS VALOR
FROM CONSULTAS C
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN ESPECIALIDADES_MEDICAS E
    ON M.ID_ESPECIALIDADE = E.ID_ESPECIALIDADE
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
WHERE UPPER(E.DESCRICAO) LIKE '%' || UPPER('&v_especialidade') || '%'
GROUP BY E.DESCRICAO;
