ACCEPT v_paciente CHAR PROMPT 'Informe o nome do paciente: '

SET PAGESIZE 200
SET LINESIZE 200

COLUMN DATA         HEADING 'DATA'  FORMAT A10
COLUMN NOME                   HEADING 'PACIENTE'      FORMAT A30
COLUMN CPF                    HEADING 'CPF'    FORMAT A30
COLUMN ENDERECO               HEADING 'ENDEREÇO'   FORMAT A30
COLUMN TELEFONE               HEADING 'TELEFONE'      FORMAT A30
COLUMN MEDICO                 HEADING 'MEDICO'         FORMAT A30
COLUMN VALOR                 HEADING 'VALOR_CONSULTA' FORMAT 9,999.99

SELECT 
    C.DATA_CONSULTA AS DATA,
    P.NOME AS NOME,
    P.CPF AS CPF,
    P.ENDERECO AS ENDERECO,
    P.TELEFONE AS TELEFONE,
    M.NOME AS MEDICO,
    PA.VALOR AS VALOR
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON C.ID_PACIENTE = P.ID_PACIENTE
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
WHERE UPPER(P.NOME) LIKE '%' || UPPER('&v_paciente') || '%';


ACCEPT v_doutor CHAR PROMPT 'Informe o nome do doutor: '

SET PAGESIZE 200
SET LINESIZE 200

COLUMN DATA         HEADING 'DATA'  FORMAT A10
COLUMN NOME                   HEADING 'PACIENTE'      FORMAT A30
COLUMN CPF                    HEADING 'CPF'    FORMAT A30
COLUMN ENDERECO               HEADING 'ENDEREÇO'   FORMAT A30
COLUMN TELEFONE               HEADING 'TELEFONE'      FORMAT A30
COLUMN MEDICO                 HEADING 'MEDICO'         FORMAT A30
COLUMN VALOR                 HEADING 'VALOR_CONSULTA' FORMAT 9,999.99

SELECT 
    C.DATA_CONSULTA AS DATA,
    P.NOME AS NOME,
    P.CPF AS CPF,
    P.ENDERECO AS ENDERECO,
    P.TELEFONE AS TELEFONE,
    M.NOME AS MEDICO,
    PA.VALOR AS VALOR
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON C.ID_PACIENTE = P.ID_PACIENTE
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
WHERE UPPER(M.NOME) LIKE '%' || UPPER('&v_doutor') || '%';


ACCEPT v_especialidade CHAR PROMPT 'Informe o nome da especialidade: '

SET PAGESIZE 200
SET LINESIZE 200

COLUMN DATA         HEADING 'DATA'  FORMAT A10
COLUMN NOME                   HEADING 'PACIENTE'      FORMAT A30
COLUMN CPF                    HEADING 'CPF'    FORMAT A30
COLUMN ENDERECO               HEADING 'ENDEREÇO'   FORMAT A30
COLUMN TELEFONE               HEADING 'TELEFONE'      FORMAT A30
COLUMN MEDICO                 HEADING 'MEDICO'         FORMAT A30
COLUMN VALOR                 HEADING 'VALOR_CONSULTA' FORMAT 9,999.99

SELECT 
    C.DATA_CONSULTA AS DATA,
    P.NOME AS NOME,
    P.CPF AS CPF,
    P.ENDERECO AS ENDERECO,
    P.TELEFONE AS TELEFONE,
    M.NOME AS MEDICO,
    PA.VALOR AS VALOR
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON C.ID_PACIENTE = P.ID_PACIENTE
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN ESPECIALIDADES_MEDICAS E
    ON M.ID_ESPECIALIDADE = E.ID_ESPECIALIDADE
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
WHERE UPPER(E.DESCRICAO) LIKE '%' || UPPER('&v_especialidade') || '%';