SET PAGESIZE 200
SET LINESIZE 200

COLUMN VALOR                 HEADING 'FATURAMENTO_TOTAL' FORMAT 9,999.99

SELECT
    SUM(PA.VALOR) AS FATURAMENTO_TOTAL
FROM CONSULTAS C
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO;