SET PAGESIZE 200
SET LINESIZE 200

COLUMN ID_CONSULTA                  HEADING 'ESPECIALIDADE' FORMAT A30
COLUMN PACIENTE              HEADING 'ESPECIALIDADE' FORMAT A30
COLUMN MEDICO              HEADING 'ESPECIALIDADE' FORMAT A30

SELECT
    C.ID_CONSULTA AS ID_CONSULTA,
    P.NOME AS PACIENTE,
    M.NOME AS MEDICO
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON P.ID_PACIENTE = C.ID_PACIENTE
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
WHERE C.ID_PAGAMENTO IS NULL;

