SET PAGESIZE 200
SET LINESIZE 200

COLUMN ID                     HEADING 'CODIGO'        FORMAT 9999
COLUMN NOME                   HEADING 'PACIENTE'      FORMAT A30
COLUMN CPF                    HEADING 'CPF'    FORMAT A30
COLUMN ENDERECO               HEADING 'ENDEREÇO'   FORMAT A30
COLUMN TELEFONE               HEADING 'TELEFONE'      FORMAT A30
COLUMN QUANTIDADE             HEADING 'NUMERO_DE_CONSULTAS' FORMAT 9999
COLUMN VALOR                 HEADING 'VALOR_TOTAL' FORMAT 9,999.99

SELECT
    P.ID_PACIENTE AS ID,
    P.NOME AS NOME,
    P.CPF AS CPF,
    P.ENDERECO AS ENDERECO,
    P.TELEFONE AS TELEFONE,
    COUNT(C.ID_PACIENTE) AS QUANTIDADE,
    SUM(PA.VALOR) AS VALOR
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON C.ID_PACIENTE = P.ID_PACIENTE
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
GROUP BY P.ID_PACIENTE, NOME, CPF, ENDERECO, TELEFONE
ORDER BY QUANTIDADE DESC;