/* CRIAÇÃO DE TABELA PACIENTES */

CREATE TABLE PACIENTES(
    ID_PACIENTE NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100),
    CPF VARCHAR2(11) UNIQUE NOT NULL,
    ENDERECO VARCHAR2(100),
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR2(15),
    CONSTRAINT PK_PACIENTES PRIMARY KEY (ID_PACIENTE)
);

/* CRIAÇÃO DE TABELA ESPECIALIDADES MÉDICAS */

CREATE TABLE ESPECIALIDADES_MEDICAS(
    ID_ESPECIALIDADE NUMBER GENERATED ALWAYS AS IDENTITY,
    DESCRICAO VARCHAR2(100),
    CONSTRAINT PK_ESPECIALIDADES PRIMARY KEY (ID_ESPECIALIDADE)
);

/* CRIAÇÃO DE TABELA MÉDICOS */

CREATE TABLE MEDICOS(
    ID_MEDICO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ESPECIALIDADE INT,
    NOME VARCHAR2(100),
    CPF VARCHAR2(11) UNIQUE NOT NULL,
    ENDERECO VARCHAR2(100),
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR2(15),
    SALARIO NUMBER(10,2) CHECK(SALARIO >= 0),
    CONSTRAINT PK_MEDICO PRIMARY KEY (ID_MEDICO),
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADES_MEDICAS(ID_ESPECIALIDADE)
);

/* CRIAÇÃO DE TABELA PAGAMENTOS */

CREATE TABLE PAGAMENTOS(
    ID_PAGAMENTO NUMBER GENERATED ALWAYS AS IDENTITY,
    STATUS VARCHAR2(100),
    VALOR NUMBER(10,2),
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO)
);

/* CRIAÇÃO DE TABELA CONSULTAS */

CREATE TABLE CONSULTAS(
    ID_CONSULTA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MEDICO INT,
    ID_PACIENTE INT,
    ID_PAGAMENTO INT,
    DATA_CONSULTA DATE,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (ID_CONSULTA),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTOS(ID_PAGAMENTO)
);

/* INSERÇÃO DE PACIENTES */

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Ana Paula Silva', '12345678901', 'Rua das Flores, 123', TO_DATE('15/03/1990', 'DD/MM/YYYY'), '11987654321');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Bruno Henrique Costa', '12345678902', 'Av. Paulista, 1000', TO_DATE('22/07/1985', 'DD/MM/YYYY'), '11991234567');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Carla Mendes Rocha', '12345678903', 'Rua Afonso Pena, 45', TO_DATE('09/11/1998', 'DD/MM/YYYY'), '21999887766');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Diego Alves Lima', '12345678904', 'Rua Dom Pedro II, 300', TO_DATE('01/01/1992', 'DD/MM/YYYY'), '31988776655');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Eduarda Ferreira Nunes', '12345678905', 'Rua Central, 89', TO_DATE('18/06/2000', 'DD/MM/YYYY'), '11995554433');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Felipe Martins Souza', '12345678906', 'Av. Brasil, 1500', TO_DATE('27/09/1987', 'DD/MM/YYYY'), '21993456789');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Gabriela Torres Pacheco', '12345678907', 'Rua do Comércio, 210', TO_DATE('04/12/1995', 'DD/MM/YYYY'), '41987651234');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Henrique Oliveira Ramos', '12345678908', 'Rua Sete de Setembro, 77', TO_DATE('30/08/1983', 'DD/MM/YYYY'), '51988770011');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('Isabela Cunha Lopes', '12345678909', 'Av. Independência, 640', TO_DATE('12/02/1999', 'DD/MM/YYYY'), '11996668888');

INSERT INTO PACIENTES (NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE)
VALUES ('João Victor Moreira', '12345678910', 'Rua Bela Vista, 55', TO_DATE('21/05/1991', 'DD/MM/YYYY'), '31990011223');

/* INSERÇÃO DE ESPECIALIDADES MÉDICAS */

INSERT INTO ESPECIALIDADES_MEDICAS (DESCRICAO)
VALUES ('Clínica Geral');

INSERT INTO ESPECIALIDADES_MEDICAS (DESCRICAO)
VALUES ('Cardiologia');

INSERT INTO ESPECIALIDADES_MEDICAS (DESCRICAO)
VALUES ('Ortopedia');

INSERT INTO ESPECIALIDADES_MEDICAS (DESCRICAO)
VALUES ('Pediatria');

INSERT INTO ESPECIALIDADES_MEDICAS (DESCRICAO)
VALUES ('Dermatologia');

/* INSERÇÃO DE MÉDICOS */

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (1, 'Ricardo Almeida Santos', '98765432101', 'Av. Paulista, 1500', TO_DATE('12/04/1978', 'DD/MM/YYYY'), '11988887777', 12000.00);

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (2, 'Mariana Lopes Ferreira', '98765432102', 'Rua das Acácias, 320', TO_DATE('25/09/1985', 'DD/MM/YYYY'), '21997776655', 18000.00);

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (3, 'Carlos Eduardo Ribeiro', '98765432103', 'Rua Dom Pedro I, 90', TO_DATE('03/02/1980', 'DD/MM/YYYY'), '31996665544', 15000.00);

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (4, 'Fernanda Azevedo Cunha', '98765432104', 'Av. Central, 780', TO_DATE('18/07/1990', 'DD/MM/YYYY'), '11995553322', 13000.00);

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (5, 'Paulo Henrique Nogueira', '98765432105', 'Rua do Comércio, 410', TO_DATE('29/11/1975', 'DD/MM/YYYY'), '41994443311', 16000.00);

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (2, 'Juliana Martins Rocha', '98765432106', 'Av. Brasil, 2200', TO_DATE('06/06/1988', 'DD/MM/YYYY'), '21993332211', 17500.00);

INSERT INTO MEDICOS (ID_ESPECIALIDADE, NOME, CPF, ENDERECO, DATA_NASCIMENTO, TELEFONE, SALARIO)
VALUES (1, 'André Luiz Pimenta', '98765432107', 'Rua Sete de Setembro, 60', TO_DATE('14/01/1982', 'DD/MM/YYYY'), '51992221100', 11000.00);


/* INSERÇÃO DE PAGAMENTOS */

INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('REJEITADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));

INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('REJEITADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));

INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('REJEITADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));

INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('REJEITADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('APROVADO', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));
INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));

INSERT INTO PAGAMENTOS (STATUS, VALOR) VALUES ('PENDENTE', ROUND(DBMS_RANDOM.VALUE(50, 2000), 2));

/* INSERÇÃO DE CONSULTAS */

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (1, 1, 1, TO_DATE('10/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (2, 2, 2, TO_DATE('11/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (3, 3, 3, TO_DATE('12/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (4, 4, 4, TO_DATE('13/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (5, 5, 5, TO_DATE('14/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (6, 6, 6, TO_DATE('15/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (7, 7, 7, TO_DATE('16/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (1, 8, 8, TO_DATE('17/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (2, 9, 9, TO_DATE('18/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (3, 10, 10, TO_DATE('19/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (4, 1, 11, TO_DATE('20/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (5, 2, 12, TO_DATE('21/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (6, 3, 13, TO_DATE('22/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (7, 4, 14, TO_DATE('23/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (1, 5, 15, TO_DATE('24/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (2, 6, 16, TO_DATE('25/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (3, 7, 17, TO_DATE('26/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (4, 8, 18, TO_DATE('27/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (5, 9, 19, TO_DATE('28/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (6, 10, 20, TO_DATE('29/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (6, 10, 21, TO_DATE('30/01/2025', 'DD/MM/YYYY'));

INSERT INTO CONSULTAS (ID_MEDICO, ID_PACIENTE, ID_PAGAMENTO, DATA_CONSULTA)
VALUES (3, 10, NULL, TO_DATE('31/01/2025', 'DD/MM/YYYY'));

/* GERAÇÃO DAS VIEWS */

/* VIEW CONSULTAS */
CREATE OR REPLACE VIEW VIEW_CONSULTAS AS
SELECT P.NOME AS PACIENTE, M.NOME AS MÉDICO, E.DESCRICAO AS ESPECIALIDADE, C.DATA_CONSULTA AS DATA, PA.VALOR
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON P.ID_PACIENTE = C.ID_PACIENTE
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN ESPECIALIDADES_MEDICAS E
    ON E.ID_ESPECIALIDADE = M.ID_ESPECIALIDADE
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO;
    
SELECT * FROM VIEW_CONSULTAS;

/* VIEW_PAGAMENTOS_PENDENTES */

CREATE OR REPLACE VIEW VIEW_PAGAMENTOS_PENDENTES AS
SELECT P.NOME AS PACIENTE, M.NOME AS MÉDICO, E.DESCRICAO AS ESPECIALIDADE, C.DATA_CONSULTA AS DATA, PA.VALOR AS PAGAMENTO_PENDENTE
FROM CONSULTAS C
INNER JOIN PACIENTES P
    ON P.ID_PACIENTE = C.ID_PACIENTE
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN ESPECIALIDADES_MEDICAS E
    ON E.ID_ESPECIALIDADE = M.ID_ESPECIALIDADE
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
WHERE PA.STATUS = 'PENDENTE';
SELECT * FROM VIEW_PAGAMENTOS_PENDENTES;

/* VIEW_FATURAMENTO_MEDICO */

CREATE OR REPLACE VIEW VIEW_FATURAMENTO_MEDICO AS
SELECT M.NOME AS MÉDICO, E.DESCRICAO AS ESPECIALIDADE, SUM(PA.VALOR) AS FATURAMENTO
FROM CONSULTAS C
INNER JOIN MEDICOS M
    ON M.ID_MEDICO = C.ID_MEDICO
INNER JOIN ESPECIALIDADES_MEDICAS E
    ON E.ID_ESPECIALIDADE = M.ID_ESPECIALIDADE
INNER JOIN PAGAMENTOS PA
    ON PA.ID_PAGAMENTO = C.ID_PAGAMENTO
GROUP BY M.NOME, E.DESCRICAO
ORDER BY FATURAMENTO DESC;
SELECT * FROM VIEW_FATURAMENTO_MEDICO;

/* DEBUG

DROP TABLE ESPECIALIDADES_MEDICAS;
DROP TABLE MEDICOS;
DROP TABLE PACIENTES;
DROP TABLE CONSULTAS;
DROP TABLE PAGAMENTOS;

*/